export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 md:py-20 font-sans">
      <h1 className="text-4xl font-playfair font-bold text-[#1F1235] mb-8">Terms of Service</h1>
      <div className="prose prose-sm text-gray-700 space-y-6">
        <p className="text-sm text-gray-500">Last Updated: {new Date().toLocaleDateString()}</p>
        
        <h2 className="text-xl font-bold text-[#7C3AED]">1. Acceptance of Terms</h2>
        <p>By accessing and using PurpleGirl, you accept and agree to be bound by the terms and provision of this agreement.</p>

        <h2 className="text-xl font-bold text-[#7C3AED]">2. User Content</h2>
        <p>You agree not to submit any questions that contain personally identifiable information, harassment, explicit content, or illegal material. We reserve the right to delete any submissions that violate these community guidelines.</p>

        <h2 className="text-xl font-bold text-[#7C3AED]">3. Medical & Professional Disclaimer</h2>
        <p>The content provided on PurpleGirl, including answers generated by our AI and moderation team, is for informational and entertainment purposes only. It is not intended to be a substitute for professional medical advice, diagnosis, treatment, or legal counsel.</p>

        <h2 className="text-xl font-bold text-[#7C3AED]">4. Intellectual Property</h2>
        <p>The PurpleGirl brand, site design, and original answering content are protected by copyright and intellectual property laws.</p>
      </div>
    </div>
  );
}
