import { Metadata } from 'next';
import Link from 'next/link';

const SITE_URL = 'https://purplegirl.in';

interface EditorialPageProps {
  params: Promise<{ lang: string }>;
}

export async function generateMetadata({ params }: EditorialPageProps): Promise<Metadata> {
  const { lang } = await params;
  const canonical = lang === 'en' ? '/editorial' : `/${lang}/editorial`;
  return {
    title: 'Editorial Policy & Standards | PurpleGirl',
    description: 'Learn about PurpleGirl Media\'s strict editorial standards, medical review processes, and commitment to providing accurate, empathetic information for Indian women.',
    alternates: { canonical, languages: { 'en': `${SITE_URL}/editorial`, 'x-default': `${SITE_URL}/editorial` } },
  };
}

export const runtime = 'edge';

export default function EditorialPage() {
  return (
    <div className="bg-pg-cream min-h-screen py-16 px-6">
      <div className="max-w-3xl mx-auto bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-pg-gray-100 font-sans">
        
        <h1 className="text-4xl font-display font-bold text-pg-gray-900 mb-2">Editorial Policy</h1>
        <p className="text-sm text-pg-gray-500 mb-8 border-b border-pg-gray-100 pb-8">
          Last Updated: {new Date().toLocaleDateString()}
        </p>

        <div className="prose prose-sm md:prose-base text-pg-gray-700 space-y-8 max-w-none">
          
          <section>
            <p className="text-lg text-pg-gray-800 font-medium">
              At PurpleGirl Media Pvt. Ltd., our mission is to provide Indian women with the most accurate, empathetic, and culturally relevant information regarding their health, relationships, career, and legal rights. 
            </p>
            <p className="mt-4">
              Because we deal with YMYL (Your Money or Your Life) topics, we hold ourselves to the highest standards of journalistic and medical integrity. Here is how we ensure the content you read is trustworthy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-pg-rose mb-3">1. Medical & Legal Review Process</h2>
            <p>
              Every piece of content categorized under Health, Mental Wellness, and Legal Rights undergoes a rigorous review process. 
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
              <li><strong>Qualified Experts:</strong> Content is reviewed by board-certified doctors, registered psychologists, or practicing advocates in India.</li>
              <li><strong>Current Guidelines:</strong> We cross-reference all claims against the latest guidelines from institutions like the ICMR, WHO, and the Supreme Court of India.</li>
              <li><strong>Clear Authorship:</strong> The specific expert who reviewed the content is clearly cited at the top and bottom of each article, along with their credentials.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-pg-rose mb-3">2. Commitment to Accuracy & Objectivity</h2>
            <p>
              We prioritize scientific evidence and legal statutes over opinion. Our editorial team ensures that content is free from cultural stigma, victim-blaming, and misinformation. If new research emerges that contradicts our existing content, we promptly update the affected articles.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-pg-rose mb-3">3. Sourcing & Citations</h2>
            <p>
              Our writers and editors are required to cite primary sources, including peer-reviewed medical journals, government websites, and official legal documents. We do not rely on unverified blogs or social media claims as factual sources.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-pg-rose mb-3">4. Privacy & Anonymity</h2>
            <p>
              Our community Q&A features are entirely anonymous to protect our users. While community questions are generated by real users, the answers provided by our platform are vetted by our editorial and expert review board to ensure no harmful advice is published.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-pg-rose mb-3">5. Corrections Policy</h2>
            <p>
              We welcome feedback from our readers and the medical/legal community. If you spot an inaccuracy or outdated information, please <Link href="/contact" className="text-pg-rose font-bold hover:underline">contact us</Link>. Our editorial team will investigate and, if necessary, issue a correction immediately.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
